platform:ios, '6.0'
pod 'CocoaLumberjack', '~> 1.8.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'SSKeychain', '~> 1.2.2'
pod 'JSBadgeView', '~> 1.3.2'
pod 'Base64nl', '~> 1.2'
pod 'KSReachability', '~> 1.4'
pod 'CHTCollectionViewWaterfallLayout', '~> 0.8'
pod 'SMPageControl', '~> 1.2'
pod 'PPRevealSideViewController', '~> 1.1.0'
pod 'NSLogger'
pod 'CocoaAsyncSocket'
pod 'SDWebImage'
pod 'libPhoneNumber-iOS', '~> 0.7.3' 
pod 'CrittercismSDK', '~> 4.1.2' 